/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subject.outline.summary;

/**
 *
 * @author laurabecker
 */
public class GenerateSummaryFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form GenerateSummaryFrame4
     */
    public GenerateSummaryFrame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lantinghei TC", 0, 30)); // NOI18N
        jLabel1.setText("Generate a summary");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 80, 304, 40);

        jLabel2.setFont(new java.awt.Font("Lantinghei TC", 0, 13)); // NOI18N
        jLabel2.setText("Word file");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 250, 74, 19);

        jLabel3.setFont(new java.awt.Font("Lantinghei TC", 0, 13)); // NOI18N
        jLabel3.setText("Calendar file");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 250, 80, 19);

        jLabel4.setFont(new java.awt.Font("Lantinghei TC", 0, 14)); // NOI18N
        jLabel4.setText("Want us to hold on to it? Sign Up.");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 300, 225, 20);

        jButton1.setFont(new java.awt.Font("Lantinghei TC", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subject/outline/summary/Images/document icon.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(110, 160, 100, 90);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subject/outline/summary/Images/calendar icon.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(260, 160, 100, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subject/outline/summary/Images/Generate box.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 120, 340, 170);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subject/outline/summary/Images/llama.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 10, 60, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateSummaryFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateSummaryFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateSummaryFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateSummaryFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateSummaryFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
